export enum ConjugationsSortDisplayEnum {
  row = 'row',
  cols = 'cols',
}

export enum ConjugationsDisplayStyleEnum {
  normalStyle = 'normalStyle',
  cardsStyle = 'cardsStyle',
}

export enum ConjugationsCinguisticEntitiesEnum {
  individual = 'individual',
  synonym = 'synonym',
  plural = 'plural',
}

export enum ConjugationsLinguisticGroupTypeEnum {
  activeVerb = 'ActiveVerb',
  passiveVerb = 'PassiveVerb',
  noun = 'Noun',
  gerund = 'Gerund',
}

export enum ConjugationsActivePassiveFixedTypeEnum {
  past = 'past',
  nominativePresent = 'nominativePresent',
  accusativePresent = 'accusativePresent',
  jussivePresent = 'jussivePresent',
  emphasizedPresent = 'emphasizedPresent',
  imperative = 'imperative',
  emphasizedImperative = 'emphasizedImperative',
}

export enum ConjugationsGerundsFixedTypeEnum {
  standards = 'standards',
  meems = 'meems',
  nomens = 'nomens',
  sourceofOrganization = 'sourceofOrganization',
}

export enum ConjugationsNounsFixedTypeEnum {
  doerName = 'doerName',
  doneActionName = 'doneActionName',
  timeAndPlaceName = 'timeAndPlaceName',
  exaggerationOfDoerName = 'exaggerationOfDoerName',
  instrumentName = 'instrumentName',
}

export enum ConjugationGerundsSecondLevelTypeEnum {
  B1 = 'B1',
  B2 = 'B2',
  B7 = 'B7',
  C1 = 'C1',
  C3 = 'C3',
  D2 = 'D2',
  E1 = 'E1',
  E2 = 'E2',
  E3 = 'E3',
  E4 = 'E4',
  F1 = 'F1',
  F2 = 'F2',
  F3 = 'F3',
  F4 = 'F4',
  H1 = 'H1',
  H2 = 'H2',
  H3 = 'H3',
  H4 = 'H4',
  H5 = 'H5',
  H6 = 'H6',
  H7 = 'H7',
  H8 = 'H8',
  J2 = 'J2',
  J3 = 'J3',
  J5 = 'J5',
  K1 = 'K1',
  K2 = 'K2',
  K3 = 'K3',
  K4 = 'K4',
  K6 = 'K6',
  K7 = 'K7',
  N2 = 'N2',
  O1 = 'O1',
  P1 = 'P1',
  P3 = 'P3',
  P4 = 'P4',
  Q2 = 'Q2',
  R2 = 'R2',
  S1 = 'S1',
  S2 = 'S2',
  S5 = 'S5',
  T2 = 'T2',
  U1 = 'U1',
  U2 = 'U2',
  U3 = 'U3',
  U5 = 'U5',
  U7 = 'U7',
  W1 = 'W1',
  W3 = 'W3',
  X1 = 'X1',
  X3 = 'X3',
  Y1 = 'Y1',
  afal = 'afal',
  ufulula = 'ufulula',
  ifiil = 'ifiil',
  faool = 'faool',
  faulula = 'faulula',
  faiel = 'faiel',
  failula = 'failula',
  faul = 'faul',
  fail = 'fail',
  faiil = 'faiil',
  faal = 'faal',
  faalula = 'faalula',
  fal = 'fal',
  falan_falana = 'falan_falana',
  falan_fala = 'falan_fala',
  falula = 'falula',
  fualula = 'fualula',
  fualla = 'fualla',
  fuulla = 'fuulla',
  fial = 'fial',
  fiiil = 'fiiil',
  filula = 'filula',
  mufall = 'mufall',
  mufalal = 'mufalal',
  mafal = 'mafal',
  mafalula = 'mafalula',
  maful = 'maful',
  mafil = 'mafil',
  mufail = 'mufail',
  mufailula = 'mufailula',
  muful = 'muful',
  mifaal = 'mifaal',
  mifal = 'mifal',
  mifalula = 'mifalula',
  mifiil = 'mifiil',
}

export enum ConjugationGerundAndNounValuesEnum {
  annexedNouns = 'annexedNouns',
  definiteNouns = 'definiteNouns',
  indefiniteNouns = 'indefiniteNouns',
}
